export const IMG_VERIFICATION_BASE_URL =
  process.env.NEXT_PUBLIC_IMG_VERIFICATION_BASE_URL;
export const IMG_VERIFICATION_API_KEY =
  process.env.NEXT_PUBLIC_IMG_VERIFICATION_API_KEY;

export const NFT_STORAGE_IPFS_KEY =
  process.env.NEXT_PUBLIC_NFT_STORAGE_IPFS_KEY;

export const INFURA_ID_ETH = process.env.NEXT_PUBLIC_INFURA_ID_ETH;

export const INFURA_ID_IPFS = process.env.NEXT_PUBLIC_INFURA_ID_IPFS;

export const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

export const ARBITER_WHITELISTER_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_ARBITER_WHITELISTER_CONTRACT_ADDR;

export const CHAINLINK_RANDOM_GENERATOR_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_CHAINLINK_RANDOM_GENERATOR_CONTRACT_ADDR;

export const DISPUTE_INITIATION_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_DISPUTE_INITIATION_CONTRACT_ADDR;

export const DECISION_NFT_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_DECISION_NFT_CONTRACT_ADDR;

export const HUDDLE_KEY =
  process.env.NEXT_PUBLIC_HUDDLE_KEY;
