export const NFT_STORAGE_IPFS_KEY =
  process.env.NEXT_PUBLIC_NFT_STORAGE_IPFS_KEY;

export const INFURA_ID_ETH = process.env.NEXT_PUBLIC_INFURA_ID_ETH;

export const INFURA_ID_IPFS = process.env.NEXT_PUBLIC_INFURA_ID_IPFS;

export const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

export const ARBITER_WHITELISTER_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_ARBITER_WHITELISTER_CONTRACT_ADDR;

export const CHAINLINK_RANDOM_GENERATOR_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_CHAINLINK_RANDOM_GENERATOR_CONTRACT_ADDR;

export const DISPUTE_INITIATION_CONTRACT_ADDR =
  process.env.NEXT_PUBLIC_DISPUTE_INITIATION_CONTRACT_ADDR;
