import { CMS_BASE_URL, queryClient } from './apiConfig';
import {
  BLOGS_FILE,
  COMMUNITY_LINK_FILE,
  EVENTS_WORKSHOPS_FILE,
  EVIDENCE_LINK_FILE,
  LAVENDER_LINK_FILE,
  LINK_FOLDER,
  LINK_WITH_IMAGE_FOLDER,
  OUR_STORY_FILE,
  RESOLVE_DISPUTE_FILE,
  TEAM_FILE,
  UNDERSTAND_YOUR_RIGHTS_FILE,
} from './dataConfig';
import {
  GA_TRACKING_ID,
  LOGIN_MODAL_ID,
  MAGIC_SECRET_KEY,
  NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY,
} from './siteConfig';

export {
  BLOGS_FILE,
  CMS_BASE_URL,
  COMMUNITY_LINK_FILE,
  EVENTS_WORKSHOPS_FILE,
  EVIDENCE_LINK_FILE,
  GA_TRACKING_ID,
  LAVENDER_LINK_FILE,
  LINK_FOLDER,
  LINK_WITH_IMAGE_FOLDER,
  LOGIN_MODAL_ID,
  MAGIC_SECRET_KEY,
  NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY,
  OUR_STORY_FILE,
  RESOLVE_DISPUTE_FILE,
  TEAM_FILE,
  UNDERSTAND_YOUR_RIGHTS_FILE,
  queryClient,
};
